### ISSUE TITLE
Add Scenario description to the Lush HTML view.

### ISSUE THREAD

**Issue by flaviasequeira** [designing-experiences/Lush.js#7]
The description of the scenario should become a part of the html Lush view.

**Comment by bobvanluijt** [comment]
@flaviasequeira Not sure what this issue is. Can you share again please.

**Comment by flaviasequeira** [comment]
The blueprint markdown contains the keyword $Scenario. The contents of this keyword are not displayed in the html view. This enhancement is for having those contents displayed.

**Comment by bobvanluijt** [comment]
A Lush blueprint always has one scenario -for now- right?

**Comment by bobvanluijt** [comment]
This is fixed.

Please note the 30min CDN delay.

**Comment by flaviasequeira** [comment]
Yes, for now.

**Comment by flaviasequeira** [comment]
Would like to see a different styling for the Scenario description. Maybe:
Writing "Scenario - " might help. 
Creating a separate block for this might help too.

Currently, it's placed out of context.

**Comment by bobvanluijt** [comment]
Additional: make it visible that the 'scenario' is about the columns underneath it.

**Comment by bobvanluijt** [comment]
This is fixed
